#You can use HEX colors with this formats: <color:#FFFFFF>
#This plugin use MiniMessage, so either you can yse every format tags from it. MiniMessage format: https://docs.advntr.dev/minimessage/format.html
#You can use internal plugin placeholders:
#1. {item} - the item for which the notification was triggered
#2. {durability} - how much durability is left

#You can find sounds names for example here: https://jd.papermc.io/paper/1.21.4/org/bukkit/Sound.html

notifications:
  required-durability: 10 #When it drops below this value, the player will receive a notification every time the durability changes.
  types:
    message: #will send notification in chat
      enabled: true
      damage-text: "&#fe6f5e&l|&r Your &#60d65e{item}&r has low durability left! It`s &#60d65e&l{durability}&r left."
      break-text: "&#fe6f5e&l|&r Your &#60d65e{item}&r is broken :("
    action-bar: #will send notification in action-bar
      enabled: true
      damage-text: "&#fe6f5e&l|&r Your &#60d65e{item}&r has low durability left! It`s &#60d65e&l{durability}&r left."
      break-text: "&#fe6f5e&l|&r Your &#60d65e{item}&r is broken :("
    sound:
      enabled: true
      damage-sound: "ITEM_CROSSBOW_HIT"
      break-sound: "ENTITY_VEX_DEATH"