#You can use HEX colors with this formats: <color:#FFFFFF>
#This plugin use MiniMessage, so either you can yse every format tags from it. MiniMessage format: https://docs.advntr.dev/minimessage/format.html
#You can use internal plugin placeholders:
#1. {item} - the item for which the notification was triggered
#2. {durability} - how much durability is left

#You can find sounds names for example here: https://jd.papermc.io/paper/1.21.4/org/bukkit/Sound.html

notifications:
  required-durability: 10 #When it drops below this value, the player will receive a notification every time the durability changes.
  types:
    message: #will send notification in chat
      enabled: true
      damage-text: "<color:#fe6f5e><bold>|</bold></color> Your <color:#60d65e>{item}</color> has low durability left! It`s <color:#60d65e>{durability}</color> left."
      break-text: "<color:#fe6f5e><bold>|</bold></color> Your <color:#60d65e>{item}</color> is broken :("
    action-bar: #will send notification in action-bar
      enabled: true
      damage-text: "<color:#fe6f5e><bold>|</bold></color> Your <color:#60d65e>{item}</color> has low durability left! It`s <color:#60d65e>{durability}</color> left."
      break-text: "<color:#fe6f5e><bold>|</bold></color> Your <color:#60d65e>{item}</color> is broken :("
    sound:
      enabled: true
      damage-sound: "ITEM_CROSSBOW_HIT"
      break-sound: "ENTITY_VEX_DEATH"

#You can set alternative names for items with default name (that have not been renamed). This is useful if you need a language other than English.
item-names:
  iron_sword: "Iron Sword"
  iron_shovel: "Iron Shovel"
  iron_pickaxe: "Iron Pickaxe"
  iron_axe: "Iron Axe"
  iron_hoe: "Iron Hoe"
  iron_helmet: "Iron Helmet"
  iron_chestplate: "Iron Chestplate"
  iron_leggings: "Iron Leggings"
  iron_boots: "Iron Boots"

  diamond_sword: "Diamond Sword"
  diamond_shovel: "Diamond Shovel"
  diamond_pickaxe: "Diamond Pickaxe"
  diamond_axe: "Diamond Axe"
  diamond_hoe: "Diamond Hoe"
  diamond_helmet: "Diamond Helmet"
  diamond_chestplate: "Diamond Chestplate"
  diamond_leggings: "Diamond Leggings"
  diamond_boots: "Diamond Boots"

  netherite_sword: "Netherite Sword"
  netherite_shovel: "Netherite Shovel"
  netherite_pickaxe: "Netherite Pickaxe"
  netherite_axe: "Netherite Axe"
  netherite_hoe: "Netherite Hoe"
  netherite_helmet: "Netherite Helmet"
  netherite_chestplate: "Netherite Chestplate"
  netherite_leggings: "Netherite Leggings"
  netherite_boots: "Netherite Boots"

  bow: "Bow"
  crossbow: "Crossbow"
  trident: "Trident"
  shield: "Shield"
  shears: "Shears"
  flint_and_steel: "Flint and Steel"
  fishing_rod: "Fishing Rod"
  elytra: "Elytra"
