name: ProjectDurability
version: '${project.version}'
main: ru.bambolumba.durabilitynotifier.ProjectDurability
api-version: '1.21'

commands:
  durability:
    description: Main plugin command

permissions:
  durability.admin:
    default: op
    description: Allows to use admin subcommand