name: DurabilityNotifier
version: '${project.version}'
main: ru.bambolumba.durabilitynotifier.DurabilityNotifier
api-version: '1.19'

commands:
  durability:
    description: Main plugin command

permissions:
  durability.admin:
    default: op
    description: Allows to use admin subcommand
  durability.notify:
    default: true
    description: Allow to receive notifications